### ISSUE TITLE
Error adding entities for domain sensor with platform ha_strava

### ISSUE THREAD

**Issue by haaino** [craibo/ha_strava#115]
Hi,

I'm getting the following message in my log file (see below), and I was wondering if I was doing something wrong or forgot the configure?

HA 2023.8 supervised version.

-----
Logger: homeassistant.components.sensor
Source: helpers/device_registry.py:191
Integration: Sensor (documentation, issues)
First occurred: 12:39:17 (2 occurrences)
Last logged: 12:39:17

Error adding entities for domain sensor with platform ha_strava
Error while setting up ha_strava platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 484, in async_get_or_create
    configuration_url = _validate_configuration_url(configuration_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 191, in _validate_configuration_url
    raise ValueError(f"invalid configuration_url '{value}'")
ValueError: invalid configuration_url ''
----

**Comment by craibo** [comment]
Hi @haaino 

I have released a bug fix for this which resolves the issue.
Please update to the latest version 3.2.24

**Comment by haaino** [comment]
Thanks. I will try right away.
