### ISSUE TITLE
YTD and ALL-time sensors not available

### ISSUE THREAD

**Issue by Crimby88** [craibo/ha_strava#119]
I got in tot 151 entities spread over 10 devices. However, no YTD or Total sensors are available.

**Comment by craibo** [comment]
Hi @Crimby88 

Are you able to share any details from your Home assistant logs that would help me triage this issue?

Thank you

**Comment by Crimby88** [comment]
Hi @craibo 
thanks for the reply. I found this in the home_assistant.log:
_2023-09-22 16:09:49.569 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ha_strava
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 503, in async_get_or_create
    configuration_url = _validate_configuration_url(configuration_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 210, in _validate_configuration_url
    raise ValueError(f"invalid configuration_url '{value}'")
ValueError: invalid configuration_url ''
2023-09-22 16:09:49.591 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.co2signal
2023-09-22 16:09:49.592 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ha_strava platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 503, in async_get_or_create
    configuration_url = _validate_configuration_url(configuration_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 210, in _validate_configuration_url
    raise ValueError(f"invalid configuration_url '{value}'")
ValueError: invalid configuration_url ''_
