### ISSUE TITLE
bad request because the redirect uri is wrong

### ISSUE THREAD

**Issue by magiva** [craibo/ha_strava#12]
the auth fails because i have specified my nabucasa url as the callback url
but when this is setting up it posts 
redirect_uri=https://my.home-assistant.io/redirect/oauth
and this is incorrect, i dont know where it gets this from but it causes a fail of bad_request

**Comment by magiva** [comment]
yes i know but the code doesnt retrieve that
my url is set correctly to the nabucasa address and its configured
correctly in the api end point.
i dont know why the code is pulling this particular uri

it worked fine on the original code (madmic i think) before that stopped
working and i found new forks.

**Comment by magiva** [comment]
yes, i changed the auth domain in strava api and it authd ok

**Comment by magiva** [comment]
but then i got comms errors in the logs

Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py",
line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  #
type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1090,
in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1120,
in _create_connection_transport
    await waiter
ConnectionResetError

**Comment by magiva** [comment]
this still doesnt work and results in error.
if i change the linking of the https://my.home-assistant.io/
to the nabu address, it returns to home assistant but with a box of 'error'

**Comment by magiva** [comment]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:417
Integration: HA Strava 2.0 (documentation, issues)
First occurred: 13:01:42 (1 occurrences)
Last logged: 13:01:42

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1120, in _create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 560, in strava_startup_functions
    await renew_webhook_subscription(
  File "/config/custom_components/ha_strava/__init__.py", line 417, in renew_webhook_subscription
    callback_response = await websession.get(url=config_data[CONF_CALLBACK_URL])
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host addressremoved.ui.nabu.casa:443 ssl:default [None]

**Comment by craibo** [comment]
Hi @magiva 

The callback url should be using the external url configured in your home assistant system settings

Could you please confirm that: 
1. On your home assistant: the external url is configured to your `nabu.casa` url
2. On Strava: The api domain is set to `my.home-assistant.io`

You should **not** change the urls on your home assistant to `my.home-assistant.io`. This is only for the domain on the Strava API

**Comment by CumpsD** [comment]
I don't have a nabu case url. I have set my external url correctly, both in HA and in Strava, yet the OAuth url still uses my.home-assistant.io in the redirect part

**Comment by CumpsD** [comment]
If I allow `my.home-assistant.io` as a callback domain in Strava, the bad request error is gone, and it seems to work.
