### ISSUE TITLE
Distance, Duration, Pace now showing -1 values after 2022.6.0

### ISSUE THREAD

**Issue by xeospeed** [craibo/ha_strava#14]
After upgrading to 2022.6.0 here's what I'm seeing in the log:

`Logger: homeassistant.config_entries
Source: custom_components/ha_strava/sensor.py:410 
Integration: HA Strava 2.0 ([documentation](https://github.com/craibo/ha_strava), [issues](https://github.com/craibo/ha_strava/issues)) 
First occurred: 12:44:53 PM (1 occurrences) 
Last logged: 12:44:53 PM

Error unloading entry Strava for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 478, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 246, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 174, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 633, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 832, in async_remove
    await self.async_will_remove_from_hass()
  File "/config/custom_components/ha_strava/sensor.py", line 410, in async_will_remove_from_hass
    super().async_will_remove_from_hass(self)
TypeError: async_will_remove_from_hass() takes 1 positional argument but 2 were given`

**Comment by craibo** [comment]
@xeospeed I have pushed some minor method param changes which will resolve the log issue.
I am still not sure what triggers all the sensors to be disabled

**Comment by craibo** [comment]
Re-opening this issue.

I managed to replicate this by updating a configuration for the Strava integration and then restarting HA.
On restart all the YTD and All time summary data sensors are disabled.

Worker Around for now:
- Re-enable the 18 sensors
- Restart HA

**Comment by foosel** [comment]
Just to give an additional data point: I'm seeing this as well. HA 2022.6.6, ha_strava 0.3.12 (but also saw it with I *think* .6? I updated in the hopes the update would fix it).

All that I can find when searching the logs for "strava" is this:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:419
Integration: HA Strava 2.0 (documentation, issues)
First occurred: 8:11:04 PM (2 occurrences)
Last logged: 8:11:19 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1120, in _create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 562, in strava_startup_functions
    await renew_webhook_subscription(
  File "/config/custom_components/ha_strava/__init__.py", line 419, in renew_webhook_subscription
    callback_response = await websession.get(url=config_data[CONF_CALLBACK_URL])
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host REDACTED.ui.nabu.casa:443 ssl:default [None]

```

This seems to be related to an initial callback failing though while the platform is still booting and the nabu casa connection not already responding. I could be mistaken though.

My sensors were all still enabled, I disabled and re-enabled, restarted, but no change, still everything sitting at -1. This worked before I restarted HA this afternoon after adding some new template sensors, so the integration was set up correctly.

**Comment by foosel** [comment]
And now it fixed itself O_O

**Comment by BertrumUK** [comment]
This works for me for the -1 issue

https://community.home-assistant.io/t/strava-home-assistant-integration/213867/78?u=bertrumuk

**Comment by ScottG489** [comment]
I'm having the -1 issue as well. When I try the method mentioned in that comment I get this error in my logs:

```
EntityRegistry can't be used in 'await' expression
```

**Comment by ScottG489** [comment]
So I was able to get things working by enabling all of the disabled entities like @craibo mentioned above. However, changing the configuration is still broken and when I try to submit it I get the following error in my logs:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 238, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_strava/config_flow.py", line 199, in async_step_init
    _entity_registry = await async_get(hass=self.hass)
TypeError: object EntityRegistry can't be used in 'await' expression
```

And if I try to reload the integration I now get this:
```
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 399, in strava_data_update_event_handler
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/ha_strava/sensor.py", line 334, in state
    pace = (self._data[CONF_SENSOR_MOVING_TIME]) / (
ZeroDivisionError: float division by zero
```

**Comment by craibo** [comment]
Thanks @ScottG489 

I will try look into these issues over the weekend and get a fix out

**Comment by jlapenna** [comment]
I think this is fixed with https://github.com/craibo/ha_strava/commit/35896f058d820fd721e033af16692099b5f579a8
