### ISSUE TITLE
"Camera" not working - exception

### ISSUE THREAD

**Issue by badguy99** [craibo/ha_strava#166]
"Camera" images from Strava are not showing up and the following error is seen in Home Assistant logs:

```
2024-06-28 10:31:47.364 WARNING (SyncWorker_62) [homeassistant.helpers.frame] Detected that custom integration 'ha_strava' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/ha_strava/camera.py, line 138: self.async_write_ha_state(), please report it to the author of the 'ha_strava' custom integration
2024-06-28 10:31:47.365 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_strava/camera.py", line 68, in image_update_listener
    camera.rotate_img()
  File "/config/custom_components/ha_strava/camera.py", line 138, in rotate_img
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'ha_strava' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/ha_strava/camera.py, line 138: self.async_write_ha_state(). Please report it to the author of the 'ha_strava' custom integration.
```

ha_strava: 3.2.35
Home Assistant: 2024.6.4

**Comment by craibo** [comment]
Hi @badguy99 

The latest version 3.2.38 should resolve these issues.
