### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by badguy99** [craibo/ha_strava#173]
this is a follow on from #166 

Unfortunately this is still not working for me. I've currently running:
ha_strava: 3.2.38
home assistant: 2024.6.4

I'm still seeing these tracebacks in the logs and the camera images are not loading:
```
2024-07-07 11:24:54.920 WARNING (SyncWorker_25) [homeassistant.helpers.frame] Detected that custom integration 'ha_strava' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/ha_strava/camera.py, line 138: self.async_write_ha_state(), please report it to the author of the 'ha_strava' custom integration
2024-07-07 11:24:54.921 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_strava/camera.py", line 68, in image_update_listener
    camera.rotate_img()
  File "/config/custom_components/ha_strava/camera.py", line 138, in rotate_img
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'ha_strava' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/ha_strava/camera.py, line 138: self.async_write_ha_state(). Please report it to the author of the 'ha_strava' custom integration.
```
I restarted HA and found the following in the logs when the system was starting up

```
2024-07-07 11:23:24.860 INFO (MainThread) [homeassistant.components.camera] Setting up ha_strava.camera
2024-07-07 11:23:24.867 ERROR (MainThread) [custom_components.ha_strava.camera] Error reading from file: file must have 'read' and 'readline' attributes
2024-07-07 11:23:24.868 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.strava_cam for domain camera with platform ha_strava
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1354, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ha_strava/camera.py", line 296, in async_added_to_hass
    self.hass.bus.async_listen(CONF_IMG_UPDATE_EVENT, await self.img_update_handler)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object method can't be used in 'await' expression
```

**Comment by craibo** [comment]
Hi @badguy99 

Please can you try latest version 3.2.39 and let me know if this resolves the issues you are experiencing?

Thank you

**Comment by badguy99** [comment]
Now running 3.2.39 with HA 2024.7.3, it's still not loading the images, but seems to have got further. Thanks for all your work on this

```
2024-07-22 14:42:31.467 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0xffff43fc5b80>, 'GET', '/uh23ZjuKghlKG68W8pIuYex1w1fOMPlkmFCWdkVh0Bk-512x288.jpg') inside the event loop by custom integration 'ha_strava' at custom_components/ha_strava/camera.py, line 220: img_response = requests.get(  # pylint: disable=unused-argument (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/craibo/ha_strava/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1559, in async_fire_internal
    self._hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 941, in async_run_hass_job
    return self._async_add_hass_job(hassjob, *args, background=background)
  File "/usr/src/homeassistant/homeassistant/core.py", line 756, in _async_add_hass_job
    task = create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/config/custom_components/ha_strava/camera.py", line 276, in img_update_handler
    if self.is_url_valid(url=img_url["url"]):
  File "/config/custom_components/ha_strava/camera.py", line 220, in is_url_valid
    img_response = requests.get(  # pylint: disable=unused-argument

2024-07-22 14:42:32.084 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ha_strava/camera.py", line 276, in img_update_handler
    if self.is_url_valid(url=img_url["url"]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_strava/camera.py", line 220, in is_url_valid
    img_response = requests.get(  # pylint: disable=unused-argument
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1347, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
    raise RuntimeError(
RuntimeError: Caught blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0xffff43fc5b80>, 'GET', '/uh23ZjuKghlKG68W8pIuYex1w1fOMPlkmFCWdkVh0Bk-512x288.jpg') inside the event loop by custom integration 'ha_strava' at custom_components/ha_strava/camera.py, line 220: img_response = requests.get(  # pylint: disable=unused-argument. (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/craibo/ha_strava/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest
```

**Comment by craibo** [comment]
Thanks @badguy99 

Those logs explain the issue much clearer. I'll try get this resolved in the week

**Comment by craibo** [comment]
Hi @badguy99 
The latest version https://github.com/craibo/ha_strava/releases/tag/3.2.40 should resolve your issues

Apologies for the delay
