### ISSUE TITLE
Unable to submit configuration of integration "Unknown error occurred"

### ISSUE THREAD

**Issue by jooojo1988** [craibo/ha_strava#24]
![strava HA](https://user-images.githubusercontent.com/70442639/181567325-722d6b7e-135e-4b07-a0ad-4cf05718bb3d.PNG)

LOG:
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/ha_strava/config_flow.py:199
Integration: HA Strava 2.0 (documentation, issues)
First occurred: 3:34:24 PM (17 occurrences)
Last logged: 3:49:09 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 238, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_strava/config_flow.py", line 199, in async_step_init
    _entity_registry = await async_get(hass=self.hass)
TypeError: object EntityRegistry can't be used in 'await' expression

**Comment by craibo** [comment]
Thanks @jooojo1988 

I will try look into these issues over the weekend and get a fix out

**Comment by spaceboy76** [comment]
yes - also seeing this

**Comment by spaceboy76** [comment]
thanks! all working

**Comment by ScottG489** [comment]
I was having this issue as well and this also fixed it for me. Thanks!
