### ISSUE TITLE
Error doing job

### ISSUE THREAD

**Issue by Chreece** [craibo/ha_strava#37]
```
Logger: homeassistant
Source: helpers/entity.py:526
First occurred: 07:54:34 (11 occurrences)
Last logged: 07:57:04

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/camera.py", line 65, in image_update_listener
    camera.rotate_img()
  File "/config/custom_components/ha_strava/camera.py", line 228, in rotate_img
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity strava_cam: https://dgtzuqphqg23d.cloudfront.net/dTrG59sGN9rEEHj1Qmv1BkRdyHREykXdk5SHjjHUCbU-512x384.jpg>
```

This error floods the Ha logs. Can I do something about it?
Thank you for your hard work!

**Comment by Chreece** [comment]
Also got this error:

```
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:520
Integration: Κάμερα (documentation, issues)
First occurred: 08:02:02 (9 occurrences)
Last logged: 08:02:02

Platform ha_strava does not generate unique IDs. ID strava_0_photos already exists - ignoring camera.strava_activity_0_photos
```

**Comment by Chreece** [comment]
The first error seems that it had to do with the option "import photos from strava" disabled
