### ISSUE TITLE
Starav custom compnent returning no data

### ISSUE THREAD

**Issue by jouster1974** [craibo/ha_strava#39]

**Comment by jouster1974** [comment]
NOticed after a recent resatrt that Im seeing zero data from my strava custom integration

Nothing had bene changed in that time, even wound things back to the last days backup just incase but exactly the same

so currently seeing this

![image](https://user-images.githubusercontent.com/15368005/199308396-ab2ed447-c5b7-4bb1-8eff-cbf75d74dbc3.png)

Logs show the following

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:198
Integration: HA Strava ([documentation](https://github.com/madmic1314/ha_strava))
First occurred: 17:57:32 (3 occurrences)
Last logged: 17:59:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 579, in async_strava_config_update_handler
    await strava_webhook_view.fetch_strava_data()
  File "/config/custom_components/ha_strava/__init__.py", line 198, in fetch_strava_data
    img_date = dt.strptime(
TypeError: strptime() argument 1 must be str, not None

I have had to make some small changes in the past to some of the custom component files but Im always doing it on the backup of helpful info rather than knowing exactly what to do without assistance

TIA
