### ISSUE TITLE
Sensors are dead?

### ISSUE THREAD

**Issue by Some1Elsewhere** [craibo/ha_strava#64]
I connected my Strava yesterday to my Home Assistant instance. Everything connection wise worked out great.

1. I can see the sensors
2. I can add them to a lovelace card there are no connection errors. 
However, it does not appear to update any values of those strava sensor. Not with previous data nor with new one. 
Do I need to "force" update or do anything other than just connect Strava to Homeassistant? 

In Strava I also do not see any REST calls/requests within my Strava API APPS Dashboard.

**Comment by craibo** [comment]
Hi @Some1Elsewhere 

I need a little more details to help you out. 

Could ask you you to do the following:
- Restart your Home assistant
- Once it's started
-- Check the sensors to see if they are working.
-- Check the Settings -> System -> Logs for anything with Strava in it and share this with me.

I can confirm the integration is currently working for me.

Thank you

**Comment by Some1Elsewhere** [comment]
Hi @craibo,
Also directly upon restarting I had this in the logs:

2022-12-18 16:45:35.412 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ha_strava which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
File "/config/custom_components/ha_strava/__init__.py", line 659, in strava_startup_functions
File "/config/custom_components/ha_strava/__init__.py", line 507, in renew_webhook_subscription
File "/config/custom_components/ha_strava/__init__.py", line 659, in strava_startup_functions
File "/config/custom_components/ha_strava/__init__.py", line 507, in renew_webhook_subscription 

`Further down the line I then got those Errors

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:507
Integration: HA Strava 2.0 (documentation, issues)
First occurred: 18. Dezember 2022 um 16:46:04 (2 occurrences)
Last logged: 18. Dezember 2022 um 16:46:09

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 505, in _sock_connect
    sock.connect(address)
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 659, in strava_startup_functions
    await renew_webhook_subscription(
  File "/config/custom_components/ha_strava/__init__.py", line 507, in renew_webhook_subscription
    callback_response = await websession.get(url=config_data[CONF_CALLBACK_URL])
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host homeassistant.local:8123 ssl:default [Invalid argument]
`

**Comment by Some1Elsewhere** [comment]
somehow I fixed it.
