### ISSUE TITLE
All sensors unavailable

### ISSUE THREAD

**Issue by whereizben** [craibo/ha_strava#95]
Hi,
I haven't looked in a few weeks, so I'm not sure when this started, but all of my strava entities now show up as unavailable.
I am running version 3.2.16 of your great integration, currently on HASS 2023.4.5, with OS 10.0. When I search the logbook for strava, I see that strava_cam keeps changing to different images, but nothing else.
I've tried removing the integration (and restarting) and reinstalling, and then doing that with a newly generated client secret, and no luck.
Thanks!

**Comment by craibo** [comment]
Hi @whereizben 

Are there any error in the logs?

There was a point where the senor naming needed to be change. Can you check on the 2 devices from the Settings -> Devices & Services -> Strava integration and check if the sensors are showing on those devices?

Thanks

**Comment by whereizben** [comment]
Hey @craibo!
When I go to Settings -> System -> Logs and search for Strava, the only error I get is below (I've removed my IP address and URL from the error) - I did remember one change I made recently, which I suspect has something to do with this, but I'm not sure how to correct the issue - I had to update the URL for my external site from https://MYDOMAIN.com:8123 to https://hass.MYDOMAIN.com:8123, and the error below does still show my old URL (without the hass. at the beginning).

I will note that when authorizing Home Assistant to connect to Strava, the final page has the server URL - I did update it there, but I believe that URL is only stored locally in my browser.

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:548
Integration: HA Strava 2.0 ([documentation](https://github.com/craibo/ha_strava), [issues](https://github.com/craibo/ha_strava/issues))
First occurred: 22:14:00 (1 occurrences)
Last logged: 22:14:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('MYIP', 8123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 699, in strava_startup_functions
    await renew_webhook_subscription(
  File "/config/custom_components/ha_strava/__init__.py", line 548, in renew_webhook_subscription
    callback_response = await websession.get(url=config_data[CONF_CALLBACK_URL])
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host MYDOMAIN.com:8123 ssl:default [Connect call failed ('MYIP', 8123)]

**Comment by whereizben** [comment]
Hey again @craibo - found the fix, I had to update the external URL within the home assistant settings, sorry about that!!
